title: "dotnet 职业技术学院"
description: Windows 10 Developer
author: "dotnet 职业技术学院"
post_author: "hucheng"
logo: https://i.loli.net/2018/09/03/5b8d178e2a6d3.jpg
github: https://github.com/easiwin
about: Windows 10 Developer
mail: 237059917@qq.com

baseurl: ""
url: "https://huchengv5.github.io/"

allowsearch: true

analytics:
  google: UA-108101550-1
disqus:
  name: huchengv5

share:
  twitter_username: lindexi_gd


enableTags: true
tagarray: []

excerpt_separator: "<!--more-->"
paginate: 15
per_page: 15
paginate_path: "/blog/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]

# Content Collection
collections:
  articles:
    output: true

# Content Template
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      author: "dotnet 职业技术学院"
      permalink: "/post/:title.html"
  - scope:
      path: "_articles"
      type: "articles"
    values:
      layout: "post"
      author: "dotnet 职业技术学院"
      permalink: "/article/:title.html"
