title: "dotnet 职业技术学院"
description: Windows 10 Developer
author: "dotnet 职业技术学院"
post_author: "胡承"
logo: https://i.loli.net/2020/09/29/9ekLD54fBASTCwc.jpg
github: https://github.com/easiwin
about: Windows Developer
mail: 237059917@qq.com

baseurl: ""
url: "https://huchengv5.gitee.io/"

allowsearch: true

analytics:
  google: UA-108101550-1
disqus:
  name: huchengv5

share:
  twitter_username: hucheng


enableTags: true
tagarray: []
excerpt_separator: "<!-- more -->"
paginate: 15
per_page: 15
paginate_path: "/blog/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]

# Content Collection
collections:
  articles:
    output: true

# Content Template
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      author: "dotnet 职业技术学院"
      permalink: "/post/:title.html"
  - scope:
      path: "_articles"
      type: "articles"
    values:
      layout: "post"
      author: "dotnet 职业技术学院"
      permalink: "/article/:title.html"
